# Generated by Django 4.2.11 on 2024-04-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=200)),
                ('descendants', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('story', 'Story'), ('comment', 'Comment')], max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.post')),
            ],
        ),
    ]
